In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [43]:
lr = LogisticRegression(solver='liblinear')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)


0.9098497495826378

In [21]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)


0.4185185185185185

In [22]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

every time we reexecute the cells the x train and x test values are changed. So we cannot run it onee timee and deecide that one model is particularly better than another model.

Thats why we use k fold cross validation. i divides the data into several parts and uses one part for testing and the rest for training . It is done for every part and then averages the accuracy every time  to decide the net accuracy of the model.

In [23]:
#as an example use number 1 to 10 as dataset
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


it uses differend training and testting sets form the folds every time

In [27]:
#a method to test the score of a model in conventionsal test split way
def get_score(model,X_train, X_test, y_train, y_test ):
    model.fit(X_train, y_train)
    return model.score(X_test,y_test)

In [28]:
get_score(lr,X_train,X_test,y_train,y_test)

c:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


0.9537037037037037

In [46]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [47]:
scores_logistic = []
scores_svm = []
scores_rf = []
#the above arrays are to save the scores of the following models

In [48]:
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(lr, X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(svm, X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(rf, X_train, X_test, y_train, y_test))

In [49]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [50]:
scores_rf

[0.9181969949916527, 0.9549248747913188, 0.9148580968280468]

In [51]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

we can do all that in a built in method cross_val_score

In [52]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [53]:
cross_val_score(svm, digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [54]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93489149, 0.94991653, 0.92153589])

Parameter tuning::